name: Trigger Webhook on Push and PR

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Flask server
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            curl -X POST -H "Content-Type: application/json" -d '{"action": "'${{ github.event_name }}'", "author": "'${{ github.actor }}'", "ref": "'${{ github.ref }}'", "timestamp": "'${{ github.event.head_commit.timestamp }}'"}' https://732d-2405-201-681a-3850-fc58-82b7-342d-a2f2.ngrok-free.app/webhook
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            curl -X POST -H "Content-Type: application/json" -d '{"action": "'${{ github.event_name }}'", "author": "'${{ github.actor }}'", "ref": "'${{ github.ref }}'", "timestamp": "'${{ github.event.head_commit.timestamp }}'"}' https://732d-2405-201-681a-3850-fc58-82b7-342d-a2f2.ngrok-free.app/webhook
          fi
      - name: Debug GitHub Context
        run: echo '${{ toJson(github) }}'